export enum RepositoryEnum {
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
  SOLICITUDSTUDENT_REPOSITORY = 'SOLICITUDSTUDENT_REPOSITORY',
  BRIEFCASESTUDENT_REPOSITORY = 'BRIEFCASESTUDENT_REPOSITORY',

}
